/**
 * Typed accessors over the build-time generated JSON. All data lives in
 * `src/generated/*.json` (regenerated by `scripts/extract-content.mjs`).
 *
 * Renamed from dsa-zth's `problems.json` to `designs.json` — the entity is a
 * Phase 4/5 case study, not a LeetCode problem.
 */

import sections from '@/generated/content.json';
import designsRaw from '@/generated/designs.json';
import scheduleRaw from '@/generated/schedule.json';
import type {
  Design,
  Difficulty,
  Schedule,
  ScheduleDay,
  StudySection,
} from '@/generated/types';

export const studySections = sections as StudySection[];
export const designs = designsRaw as Design[];
export const schedule = scheduleRaw as Schedule;

export function findStudySection(slug: string): StudySection | undefined {
  return studySections.find((s) => s.slug === slug);
}

export function findDesign(slug: string): Design | undefined {
  return designs.find((d) => d.slug === slug);
}

export function findDesignById(id: string): Design | undefined {
  return designs.find((d) => d.id === id);
}

export function findStudySectionById(id: string): StudySection | undefined {
  return studySections.find((s) => s.id === id);
}

export function scheduleDay(day: number): ScheduleDay | undefined {
  return schedule.find((d) => d.day === day);
}

export function scheduleAround(
  day: number,
  before = 0,
  after = 2,
): ScheduleDay[] {
  return schedule.filter((d) => d.day >= day - before && d.day <= day + after);
}

export function studySectionsByPhase(): Record<string, StudySection[]> {
  const map: Record<string, StudySection[]> = {};
  for (const s of studySections) {
    (map[s.phaseId] ??= []).push(s);
  }
  return map;
}

export function designsByPhase(): Record<string, Design[]> {
  const map: Record<string, Design[]> = {};
  for (const d of designs) {
    (map[d.phaseId] ??= []).push(d);
  }
  return map;
}

export const ALL_DIFFICULTIES: Difficulty[] = ['Easy', 'Medium', 'Hard'];

/**
 * For system-design "patterns" spans all Phase 1 building blocks + Phase 2
 * distributed concepts + Phase 3 design patterns (24 total) — surfaced via
 * each design's `pattern` field.
 */
export function allPatterns(): string[] {
  const set = new Set<string>();
  for (const d of designs) {
    if (d.pattern) set.add(d.pattern);
  }
  return [...set].sort();
}

export function allCompanies(): string[] {
  const set = new Set<string>();
  for (const d of designs) {
    if (!d.companies) continue;
    for (const c of d.companies.split(',').map((s) => s.trim())) {
      if (c) set.add(c);
    }
  }
  return [...set].sort();
}

export function allConcepts(): string[] {
  const set = new Set<string>();
  for (const d of designs) {
    if (!d.concepts) continue;
    for (const c of d.concepts.split(',').map((s) => s.trim())) {
      if (c) set.add(c);
    }
  }
  return [...set].sort();
}

export function allModules(): Array<{
  phaseId: string;
  moduleId: string;
  moduleTitle: string;
  count: number;
}> {
  const map = new Map<
    string,
    { phaseId: string; moduleId: string; moduleTitle: string; count: number }
  >();
  for (const d of designs) {
    const key = `${d.phaseId}:${d.moduleId}`;
    const existing = map.get(key);
    if (existing) {
      existing.count++;
    } else {
      map.set(key, {
        phaseId: d.phaseId,
        moduleId: d.moduleId,
        moduleTitle: d.moduleTitle,
        count: 1,
      });
    }
  }
  return [...map.values()];
}

export type { Design, Difficulty, Schedule, ScheduleDay, StudySection };
